### ISSUE TITLE
The web site for Livecharts is not working. Me as a paying customer can not access my account or set licenses to my team

### ISSUE THREAD

**Issue by STichelaar** [Live-Charts/Live-Charts#1119]
#### How to reproduce?

The web site for Livecharts is not working. Me as a paying customer can not access my account or set licenses to my team.
This has been an issue for a very long long time. 

Please Fix this so payed customers can actually use your geared charts library!!

#### Extra notes

Seems clear to me. If you ask money for something, services should be provided

**Comment by beto-rodriguez** [comment]
@STichelaar feel free to take a look to the guide:

https://lvcharts.net/licensing/howto

If you are facing any issue you can send a mail to support@lvcharts.net and you will get help.
