### ISSUE TITLE
How can I format the ToolTip values without change my AxisX label values?

### ISSUE THREAD

**Issue by zeehtecnologia** [Live-Charts/Live-Charts#627]
#### How to reproduce?

Hello everybody! I'm new to GitHub, so please sorry if i'm out of rules...
Well, i'm trying to create a custom tooltip, actually i'm designing a cartesianChart, with one Serie, where Axis X value is DateTime and Y value is Double.
I'm also formatting the AxisX to "HH:00".
Everything works OK, but when a point is hovered, it shows the rounded time (like 15:00 or 16:00) and I need it to show minute by minute.. But just on the Tooltip..

I have searched a lot in the documentation and in the issues here... But some pages are off, and other documentations talk about how to do in WPF, with VM. And I don't have knowledge in WPF.

Can anyone help me?

#### Extra notes

I also tried change the LabelFormatter from AxisX to minute, but collapse all the minutes on the Axis..

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>Latest</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.0</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by zeehtecnologia** [comment]
Sorry, I solved it just removing the Separator...

Can I ask for change colors here?

**Comment by zeehtecnologia** [comment]
Hello again! I need to change the formatter on the tooltip to another format instead of "HH:mm", but keeping the formatter on AxisX.
How can I do it?

**Comment by beto-rodriguez** [comment]
I think you can use the `PointLabel` property, even it might work, I think this is not intuitive and could be much better.

Keeping this open to fix in the next version.
