### ISSUE TITLE
Multiple Gauge-s on one view.

### ISSUE THREAD

**Issue by sekulicb** [Live-Charts/Live-Charts#720]
Hi. When you put Gauge into reusable UserControl and then use that UserControl multiple times on one screen, only the last one is not animated (in my case). For example lets say I have MainWindow.xaml. That MainWindow has Grid with three columns. Each column is one UserControl with its own ViewModel. Each user controls contains only Title (regular TextBlock) and Gauge control. 

From and To properties are set to "0" and "100" in XAML. Only Value property is binded to ViewModel.

I expected that all Gauge controls will animate independently since they have different values but only Gauge in third column is not animated. If I remove that third column completely then second Gauge control is only one animated. This is really weird behavior. 

I am using:

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7 LiveCharts.Wpf</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.2 NET Framework</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by sekulicb** [comment]
Quick follow up:

It appears that when I remove binding from Gauge control, all three Gauges are animated and work as they should. So to sum it up, it's not because I have multiple Gauge-s on one Window as I initially thought, binding itself is the problem. When Value property is added in XAML everything works. That means that I cannot dynamically changed it thru ViewModel. Is this going to be fixed soon because I need this library imported into two commercial products ?

**Comment by TheDuze** [comment]
Hi. I have the exact same issue. I have a user control with two gauges on it. Like a widget. When I insert multiple of the same widget all but the very last is updated. The value seems to change for me, but the color or gauge does not animate. Maybe the color is correct but the gauge does not animate, so I'm not able to see it.


Live chart 0.9.7
.Net 4.6.2
Windows 7

**Comment by sekulicb** [comment]
I don't see a workaround. Can you edit ?

**Comment by sekulicb** [comment]
Thanks. We'll probably have to wait for LiveCharts 1.0. version to be done. Looks like its coming this month.

**Comment by sekulicb** [comment]
Closing because we didn't move further from this.
