### ISSUE TITLE
When showing 150k data using Column Chart. Its blocking the UI?

### ISSUE THREAD

**Issue by R1zwan** [Live-Charts/Live-Charts#742]
When showing 150k data using Column Chart. Its blocking the UI?

**Comment by beto-rodriguez** [comment]
Hello

can you please tell me if you arwe using the geared package?

The open source version is not designed to support many data

**Comment by R1zwan** [comment]
At present I am using open source. Can you please let me know how much max
data is supported by open source library?

Regards

Rizwan

**Comment by beto-rodriguez** [comment]
Give it a try, it depends on the series you are using you can install it from Nuget.

**Comment by R1zwan** [comment]
I am already using Open source as said above and also using Column Series, hence i notice this behavior,
can you let me know whats the max number of data is supported by Column series in Open source library?

Regards
