### ISSUE TITLE
How to set YAxis to int?

### ISSUE THREAD

**Issue by R1zwan** [Live-Charts/Live-Charts#773]
Auto calculated YAxis values always display in decimal. I want only whole number i.e., Integer value ?

**Comment by beto-rodriguez** [comment]
Use the Axis.LabelFormatter property

    axis.LabelFormatter = x => x.ToString("N0");

**Comment by R1zwan** [comment]
It displays as below : 
![error](https://user-images.githubusercontent.com/13550406/39179429-f1819684-47d1-11e8-8aab-4a31586092b6.PNG)

**Comment by beto-rodriguez** [comment]
Try also

   axis.Step = 1;

**Comment by R1zwan** [comment]
is Y axis value is more than 100 it becomes rigid as it adds 1,2,3,4... till 100. Its unaccepted.

**Comment by beto-rodriguez** [comment]
Then calculate the step, make it acceptable according to your range, the current approach tries to guess the best step, if you have a different need then calculate it by your self.
