### ISSUE TITLE
Hiding the axis labels but keep the separators visible

### ISSUE THREAD

**Issue by ChrisLawford** [Live-Charts/Live-Charts#778]
It would be great if you could hide the Labels of an axis and just keep the separators visible. this proves to be very useful in situations where the actual values are not of worth but the relative distances, i.e. those seen by the line spacing, can be very useful.

My current desire is due to the nature of creating a grid using the livechart. Each of the axis has a separator with step 1 and if I could only show the lines that make up the grid it would be perfect.
```
   <lvc:CartesianChart.Series >
           <lvc:ScatterSeries Title="Triggers" Values="{Binding TriggerValues}" />
   </lvc:CartesianChart.Series>
   <lvc:CartesianChart.AxisX>
           <lvc:Axis 
                         ShowLabels="True">
                     <lvc:Axis.Separator>
                             <lvc:Separator StrokeThickness="1" Step="1" IsEnabled="True"/>
                     </lvc:Axis.Separator>
           </lvc:Axis>
    </lvc:CartesianChart.AxisX>
```

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*0.9.7*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.61*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*10 pro*</td>
</tr>
</table>

**Comment by Notts90** [comment]
If you don't mind losing the axis title as well, an intermediate solution could be to set the brush to transparent.

    <lvc:CartesianChart>
        <lvc:CartesianChart.AxisX>
            <lvc:Axis Foreground="Transparent"/>
        </lvc:CartesianChart.AxisX>
    </lvc:CartesianChart>

**Comment by ChrisLawford** [comment]
Perfect, happy with that :)
