### ISSUE TITLE
how to fill color between two LineSeries ?

### ISSUE THREAD

**Issue by zhongbodong** [Live-Charts/Live-Charts#787]
#### How to reproduce?

*i want to fill color between two LineSeries,but i dont know how to do this . *

#### Extra notes

*i want to show like this just fill between two series:
![6j zz vb wuw 9ar b 25g7](https://user-images.githubusercontent.com/28446826/39790462-e5430b1c-5368-11e8-9230-d1ecbc159b23.png)
but if i set  below series color to Transparent.and set top series to blue ,it will show like above
*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*0.9.7.0*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.6*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*win7*</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This would require a new series type, for now it is not supported.

**Comment by zhongbodong** [comment]
Can I achieve the following results?
![qq    @@@20180509155756](https://user-images.githubusercontent.com/28446826/39802897-e5645310-53a1-11e8-9ee1-2c3ae551f597.png)
@beto-rodriguez
