### ISSUE TITLE
Alternates of building FAQs Chat Bot.

### ISSUE THREAD

**Issue by omairzia** [Live-Charts/Live-Charts#795]
Hello Guys,

I have a requirement to create a chat bot that can answer the questions of users. The scenario is the system get data from PDFs that contains a bunch of information related to different topics and build a model. When user come to the chat bot and asks a question the chat bot extract the relevant answer from the PDFs and response back to the user. I have reviewed one of the Microsoft Cognitive Service called QnA maker but QnA maker does not train by its own self I have to extract the piece of information from PDFs and train the QnA maker by my own self.

#### Example:

You may consider the example that I have a PDF with information about Credit Card. Like in a paragraph it states that ‘You may apply for the Credit Card directly from our web site. The bank sends the Credit Card to your postal addresses’. Now if user ask that ‘How can I apply for Credit Card?’ then system extract its answer from PDFs and response ‘You may apply for Credit Card directly from our web site.’ In the same way if user asks ‘how I can collect my Credit Card?’ then system would answer ‘The bank sends the Credit Card to your postal addresses.’

I have reviewed the Microsoft Cognitive Services but did not get any relevant service to get this task done. In these services we have to train the system by our own self. So please let me know, what are the alternates (we might have to build a python or other program to get it done) that I get it done?

**Comment by li0nsar3c00l** [comment]
Why the hell is this issue not closed already?
