### ISSUE TITLE
How to fixed VisualElement Position in LiveCharts?

### ISSUE THREAD

**Issue by zhongbodong** [Live-Charts/Live-Charts#820]
#### How to reproduce?

*In my Wpf Application,i used a VisualElement to show Warning Tips in livecharts like this:

![image](https://user-images.githubusercontent.com/28446826/42253598-01e759a2-7f75-11e8-955d-694d03fe6fab.png)
 VisualElement according to X,Y to fix it position, but in my application,the X is always change， Interval is 1 second，so i want to fixed VisualElement position*

#### Extra notes

* i have tried it：
` //private void TimerOnTick(object sender, EventArgs e)
        //{

        //    cartesianChart1.VisualElements.Remove(v2);   
        //    v2 = new VisualElement
        //    {
        //        X = DateTime.Now.Ticks,
        //        Y = 200,
        //        HorizontalAlignment = HorizontalAlignment.Left,
        //        VerticalAlignment = VerticalAlignment.Top,
        //        UIElement = new TextBlock //notice this property must be a wpf control
        //        {
        //            Text = "Designed Upper Limit 設計上限值!",
        //            FontWeight = FontWeights.Bold,
        //            HorizontalAlignment = HorizontalAlignment.Center,
        //            Foreground = Brushes.White,
        //            FontSize = 16,
        //            Opacity = 0.6
        //        }
        //    };
        //    cartesianChart1.VisualElements.Add(v2);`
//}

it will disappear then appear，i do not want it
*

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>*0.9.7.0*</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>*4.6.0*</td>
</tr>
<tr>
    <td>Windows</td>
    <td>*win7*</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
This is a WPF concept.

A visual element in LiveCharts helps you to place any FrameworkElement object in a chart and relative to the chart current scale.

If you just need a fixed element above the chart then things are easier, just use WPF you don't need LiveCharts, this is a WPF issue and is out of the scope of this library.

Let me know if I misunderstood the question, i'll close this for now.
