### ISSUE TITLE
Mapper doesn't work with GearedValues

### ISSUE THREAD

**Issue by MarkusSchoedl** [Live-Charts/Live-Charts#825]
Hello,
First of all i want to say that I like this library very much. You can clearly see that alot of effort has been put into it. 

However I am experiencing a problem with Live-Charts Geared using a Mapper (WinForms).
The goal is to print a simple chart where every value should be greater than the value before. If thats not the case, it should be highlighted with a red circle.
However, since i need to print thousands of values in one chart, i've decided to use the Geared Library.
But when i change the `ChartValues `to `GearedValues `the mapper seems to stop changing the Stroke of the Circles.

I am not sure if its a Bug or i'm just using the Library wrong.

Here you can see how it looks without the `GearedValues` (This is real data):
![capturechart](https://user-images.githubusercontent.com/32414751/42315394-9fee7856-8047-11e8-9310-8641f23c5fdb.PNG)

Here is my Code:

```
IChartValues points = new GearedValues<ObservablePoint>();
ObservablePoint[] observables = new ObservablePoint[lData.Count];
for (int i = 0; i < lData.Count; i++)
{
    observables[i] = new ObservablePoint(lData[i].range, lData[i].elevation);
}
points.AddRange(observables);

// Circles around bad Values
List<int> pointsToHighlight = GetIndizesOfWrongDirections(observables);
System.Windows.Media.Brush DangerBrush = new SolidColorBrush(System.Windows.Media.Color.FromRgb(238, 62, 60));

var mapper = Mappers.Xy<ObservablePoint>()
    .X((point) => point.X)
    .Y((point) => point.Y)
    .Stroke((item, index) => pointsToHighlight.Contains(index) ? DangerBrush : System.Windows.Media.Brushes.Transparent);

var scatter = new GLineSeries(mapper)
{
    Configuration = mapper,
    Values = points,
    PointGeometry = DefaultGeometries.Circle,
    PointForeground = System.Windows.Media.Brushes.Transparent,
    PointGeometrySize = 7,
    StrokeThickness = 1,
};

SeriesCollection seriesCollection = new SeriesCollection()
{
    scatter
};

chart.Series = seriesCollection;
chart.Update(true, true);
```

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>v0.9.7</td>
</tr>
<tr>
    <td>Live-Charts Geared version</td>
    <td>v1.2.9</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>.NET Framework 4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Version 6.1 (Build 7601: Service Pack 1)</td>
</tr>
</table>

Best Regards

**Comment by beto-rodriguez** [comment]
Hi

I am sorry this feature is not supported in the geared package in version 0, version 1 supports it, but is not ready yet.

please notice this is mentioned in the geared package banner

https://lvcharts.net/licensing/pricing

at Do LiveCharts.Geared support all the features LiveCharts does?
