### ISSUE TITLE
Change charts circles size

### ISSUE THREAD

**Issue by Miro382** [Live-Charts/Live-Charts#826]
Hi,
I want change size of all legend and tooltip circles in Live Charts. I searched all documentation but I don't know how it is called. How to change size of every circle in tooltip and legend?

```
PieChart pieChart = new PieChart();
pieChart.Width = 400;
pieChart.Height = 300;

pieChart.LegendLocation = LegendLocation.Bottom;

PieSeries pieSeries = new PieSeries();
pieSeries.Values = new ChartValues<int> { 5 };
pieSeries.Title = "A";
pieSeries.DataLabels = true;

PieSeries pieSeries2 = new PieSeries();
pieSeries2.Values = new ChartValues<int> { 3 };
pieSeries2.Title = "B";
pieSeries2.DataLabels = true;

PieSeries pieSeries3 = new PieSeries();
pieSeries3.Values = new ChartValues<int> { 6 };
pieSeries3.Title = "C";
pieSeries3.DataLabels = true;

pieChart.Series.Add(pieSeries);
pieChart.Series.Add(pieSeries2);
pieChart.Series.Add(pieSeries3);
```
![obrazok](https://user-images.githubusercontent.com/20913015/42336069-c3314a56-8082-11e8-8366-5abb454dfd27.png)

**Comment by CalebEdhouse** [comment]
I know it can be set it the XAML if that helps? Saw it in one of the examples.
'''
            <lvc:PieChart Name="myPieChart" Series="{Binding SeriesCollection}">
                <lvc:PieChart.ChartLegend>
                    <lvc:DefaultLegend BulletSize="20"></lvc:DefaultLegend>
                </lvc:PieChart.ChartLegend>
                <lvc:PieChart.DataTooltip>
                    <lvc:DefaultTooltip BulletSize="20"></lvc:DefaultTooltip>
                </lvc:PieChart.DataTooltip>
            </lvc:PieChart>

**Comment by Miro382** [comment]
I found it thanks: 
```
                        PieChart pieChart = new PieChart();
                        ((DefaultLegend)pieChart.ChartLegend).BulletSize = 50;
                        ((DefaultTooltip)pieChart.DataTooltip).BulletSize = 50;
```
