### ISSUE TITLE
How to save a Cartesian Chart as image, in Winforms

### ISSUE THREAD

**Issue by rhp9** [Live-Charts/Live-Charts#827]
Hello, been working with live charts for a week , i am trying to save a Cartesian chart as an image in win forms, Tried with DrawToBitmap(), but chart gets crop in half, and i do not know what to do. Can not use WPF example because Win Forms does not allow FrameworkElement class. Thanks in advance

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>WinForms.0.9.7.1</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.5</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
You should be able to, the WinForms control is just a WPF control hosted in an ElementHost, so when you are using LiveCharts in WinForms, the NuGet package adds the required assemblies use any WPF object in WinForms. give it a try again.
