### ISSUE TITLE
Y Axis labels aren't rendered when axis is mirrored

### ISSUE THREAD

**Issue by cjmurph** [Live-Charts/Live-Charts#837]
Hi, I need to show a line chart where the Y axis is upside down (minimum value at the top, maximum at the bottom. I've achieved this by setting the max and min values on the Y axis so min is greater than max.

#### How to reproduce?

Swap max and min values on y axis to invert the data (lowest value is on top, largest to bottom).

`<wpf:Axis MaxValue="1" ShowLabels="True" MinValue="10" Title="Position" Labels="{Binding ChartYLabels}"/>`

No labels are rendered. Switching the max and min values so max is greater than min works as expected

#### Extra notes

The labels should render to match the now inverted data.

Everything else about the chart works as expected.

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.6.1</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Win7 64</td>
</tr>
</table>

**Comment by thundermann** [comment]
I second this issue.

**Comment by beto-rodriguez** [comment]
See https://github.com/Live-Charts/Live-Charts/issues/948
