### ISSUE TITLE
hello, Gantt View, more than one value for Task

### ISSUE THREAD

**Issue by qzwzqty** [Live-Charts/Live-Charts#840]
hello:
How can I achieve this Charts? Thanks!

![snipaste_2018-08-11_23-08-27](https://user-images.githubusercontent.com/23160268/43998282-a69ef662-9e24-11e8-9e8b-23e2b6f1c6a8.png)
![snipaste_2018-08-12_11-39-48](https://user-images.githubusercontent.com/23160268/43998283-ae1c69b0-9e24-11e8-8641-a4b9664cdf5e.png)

**Comment by SongFuZhen** [comment]
Hi, I have this question too. and I solve it by visual elements.

the main code like this:

![image](https://user-images.githubusercontent.com/13480950/83587658-226b2480-a582-11ea-8960-3493184262e0.png)

**Comment by qzwzqty** [comment]
@SongFuZhen Thanks.
