### ISSUE TITLE
https://lvcharts.net/ is down!!!

### ISSUE THREAD

**Issue by jsirsch** [Live-Charts/Live-Charts#871]
#### How to reproduce?

Got to https://lvcharts.net/

#### Extra notes

_Please fix this problem! The Website is very helpful for developing._
@beto-rodriguez

**Comment by beto-rodriguez** [comment]
I have no idea what is wrong in the site... need to check it with the hosting provider.. i am on it

**Comment by beto-rodriguez** [comment]
Site is up now, thanks for reporting
