### ISSUE TITLE
Microsoft Bot Web Channel UI language is not changing.

### ISSUE THREAD

**Issue by omairzia** [Live-Charts/Live-Charts#875]
Hello,
I am currently having an issue and I have searched a lot but not get any solution yet.
Actually, I have developed a BOT for french language and it is working fine an my local with Bot Emulator (see the highlighted text). While if I deploy it on azure and try to chat through web chat channel its not showing me the UI in french (please see the below image) all the labels are in french. Could anybody help me, what should I do to change UI in french too. Just to let you know my browser's and laptop locale settings are set as FR (french) but still it is not showing french labels on UI.

#### Local Bot Emulator
![image](https://user-images.githubusercontent.com/17113413/46718991-5c3d3800-cc86-11e8-96df-6ebc8004e028.png)

#### Web Chat
![image](https://user-images.githubusercontent.com/17113413/46719349-2482c000-cc87-11e8-87db-cc08a398a569.png)

**Comment by riQQ** [comment]
Wrong repository.

**Comment by omairzia** [comment]
The issue has been resolved by just adding the **l=fr-FR** at the end of the web chat URL.
