### ISSUE TITLE
Axe X disappear with StackedRowSeries

### ISSUE THREAD

**Issue by dimitriBouteille** [Live-Charts/Live-Charts#926]
## How to reproduce?

When I do this : 

```C#
this.GroupCollection[PositionInCollection].Values.Add(8d);
this.GroupCollection[PositionInCollection].Values.Add(8);
```

![Chart work](https://i.ibb.co/hgF0Xvz/chart-Work.png)

Axe X is visible

But when I do this : 

```C#
this.GroupCollection[PositionInCollection].Values.Add((double)ValueGroup.Value);
```

ValueGroup is Dictionnary with ValueGroup.Value type double
![Chart bug](https://i.ibb.co/1vwvHFd/chartBug.png)

Axe X disappear :(

## I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>LiveCharts.0.9.7</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10</td>
</tr>
</table>

**Comment by Brains** [comment]
My workaround https://github.com/Live-Charts/Live-Charts/issues/802#issuecomment-491014737. Enjoy.

**Comment by dimitriBouteille** [comment]
Solution here : https://github.com/Live-Charts/Live-Charts/issues/802
