### ISSUE TITLE
After inverted Y axis with LiveCharts, Y axis label Not Showing

### ISSUE THREAD

**Issue by kuldip1490** [Live-Charts/Live-Charts#948]
here my Code
`
 Series = new SeriesCollection();

            var r = new Random();

            for (var i = 0; i < 10; i++) // 30 series
            {

                var trendY = 0d;
                var trendX = 0d;
                //var values = new double[90000];
                List<ObservablePoint> List_X_Y = new List<ObservablePoint>(90000);
                ChartValues<ObservablePoint> objChartValues = new ChartValues<ObservablePoint>();

                for (var j = 0; j < 90000; j++) // 10k points each
                {
                    trendX += (r.NextDouble() < .8 ? 1 : -1) * r.Next(0, 10);
                    trendY += (r.NextDouble() < .5 ? 1 : -1) * r.Next(0, 20);
                    //values[j] = trend;
                    List_X_Y.Add(new ObservablePoint() { X = trendX, Y = trendY });
                }

                objChartValues.AddRange(List_X_Y);

                double _minY = List_X_Y.Min(x => x.Y);
                double _maxY = List_X_Y.Max(x => x.Y);

                //// Comapre
                if (_maxY > maxY)
                {
                    maxY = _maxY;
                }
                if (_minY < minY)
                {
                    minY = _minY;
                }

                var series = new GLineSeries
                {
                    Values = objChartValues.AsGearedValues().WithQuality(Quality.Low),
                    Fill = System.Windows.Media.Brushes.Transparent,
                    StrokeThickness = 1,
                    Visibility = System.Windows.Visibility.Visible,
                    PointGeometry = null //use a null geometry when you have many series

                };
                Series.Add(series);
                cartesianChart1.Series.Add(series);
            }

            //// Add X & Y axis

            Axis objXAxis = new Axis();
            objXAxis.Title = "Time Duration";

            Axis objYAxis = new Axis();
            objYAxis.Title = "Depth";

            objYAxis.MinValue = maxY;
            objYAxis.MaxValue = minY;

            cartesianChart1.AxisX.Add(objXAxis);
            cartesianChart1.AxisY.Add(objYAxis);

            cartesianChart1.Refresh();`

#### Extra notes
here my output

![image](https://user-images.githubusercontent.com/22524273/57121842-b115dc80-6d97-11e9-8da6-87644c46a7e2.png)

I need help ..... @beto-rodriguez 
#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7.0</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.7.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>10</td>
</tr>
</table>

**Comment by beto-rodriguez** [comment]
Hi

Please checkout the following article,

https://stackoverflow.com/questions/43998994/c-sharp-how-to-invert-y-axis-with-live-charts

This shows the correct way to invert an axis.

Regards!
