### ISSUE TITLE
Live Charts Wpf doesn't show all X-Axis Labels

### ISSUE THREAD

**Issue by RaoHammas** [Live-Charts/Live-Charts#955]
I am using Live charts wpf to draw some charts. To make each column bar of different color i am adding multiple series. but it doesn't show x-axis labels of all series. Why ?
```C#
senderChart.Series = new SeriesCollection();
    int i = 0;
   var ax = new Axis
   {
       Separator = new LiveCharts.Wpf.Separator()
       {
           Step = 1
       },
       Labels = dateValues,
       ShowLabels = true
   };
   senderChart.AxisX.Add(ax);
    foreach (var val in dataValues)
    {
        senderChart.Series.Add(new ColumnSeries
        {
            DataLabels = true,
            Title = dateValues[i],
            Values = new ChartValues<double>{val},
        });
        i++;
    }  
```

I also have tried almost every different way of assigning series to chart but still got same result.
![Annotation 2019-05-17 115631](https://user-images.githubusercontent.com/16499626/57909550-88fca200-789c-11e9-9cda-f77d11fc4476.jpg)

**Comment by RaoHammas** [comment]
Using mappers and single series solved my problem !

**Comment by fatihyildizhan** [comment]
@RaoHammas Is it possible to share the Mappers Example? I couldn't figure it out how to use it.
