### ISSUE TITLE
LiveCharts with vb winform project

### ISSUE THREAD

**Issue by Julien-Faure** [Live-Charts/Live-Charts#976]
#### My problem

I want use LiveCharts in my vb winform project but i have lot of problem when i try to use it.

Is it possible to use LiveCharts in vb ?

If you had already use LiveCharts in vb project, can you help me ?

#### I am using

<table>
<tr>
    <td>Live-Charts version</td>
    <td>0.9.7</td>
</tr>
<tr>
    <td>.Net Version</td>
    <td>4.7.2</td>
</tr>
<tr>
    <td>Windows</td>
    <td>Windows 10 64 bits</td>
</tr>
</table>

**Comment by parotech123** [comment]
Hi! yes it is possible to use livecharts in vb. I am currently using it. What problem are you facing?

**Comment by Julien-Faure** [comment]
Hi

When I try to import a control chart, I've an error about missing methods. I imported many times the librairy (with Nuget or git repestory) but the problem still persists.

I use VisualStudio 2018, I don't know if the problem comes from that.

I try to use LiveCharts in new project but nothing changes.

**Comment by parotech123** [comment]
Please post the errore, so it is easier to understand

**Comment by Julien-Faure** [comment]
I created a new project for you show my errors but, for a unknow reason, it's work now. I don't undertand why.

But thank you for your help.
